language: cpp
os: 
#    - linux
    - osx
compiler:
    - gcc
#    - clang

osx_image: xcode61

before_install:
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo add-apt-repository "deb http://us.archive.ubuntu.com/ubuntu/ trusty main universe multiverse"; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update; fi

install:
    - if [[ $TRAVIS_OS_NAME == 'linux' && $CXX == 'clang++' ]]; then sudo apt-get install --no-install-recommends clang-3.5; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' && $CXX == 'g++'     ]]; then sudo apt-get install --no-install-recommends g++; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install --no-install-recommends libhdf5-7; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install --no-install-recommends libpango-1.0-0 libpangocairo-1.0-0 libhdf5-dev; fi
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install --no-install-recommends -t trusty -y libboost-thread-dev libboost-timer-dev libblitz0-dev gnuplot-nox libhdf5-serial-dev cmake libgnuplot-iostream-dev; fi
    #- if [[ $TRAVIS_OS_NAME == 'osx' && $CXX == 'clang++' ]]; then brew install llvm --with-clang; fi
    #- if [[ $TRAVIS_OS_NAME == 'osx' && $CXX == 'g++' ]]; then brew install gcc48; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then sudo brew tap homebrew/science; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install gnuplot blitz; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install hdf5 --with-cxx; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew reinstall boost --with-c++11; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then wget -O /usr/local/include/gnuplot-iostream.h http://gitorious.org/gnuplot-iostream/gnuplot-iostream/raw/gnuplot-iostream.h; fi

script:
    # libmpdata++
    - mkdir build 
    - cd build
    - if [[ $TRAVIS_OS_NAME == 'linux' && $CXX == 'clang++' ]]; then cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ ../; fi # Travis default is not the packaged one
    - if [[ $TRAVIS_OS_NAME == 'osx' && $CXX == 'clang++' ]]; then cmake -DCMAKE_CXX_COMPILER=/usr/local/bin/clang++ ../; fi # Travis default is not the packaged one
    - if [[ $TRAVIS_OS_NAME == 'osx' && $CXX == 'g++' ]]; then cmake -DCMAKE_CXX_COMPILER=g++-4.8 ../; fi # the one from homebrew
    - cmake -DCMAKE_BUILD_TYPE=Debug ../
    - VERBOSE=1 make -C tests/unit
    - OMP_NUM_THREADS=4 make -C tests/unit test || cat tests/unit/Testing/Temporary/LastTest.log / # "/" intentional! (just to make cat exit with an error code)
    - cmake -DCMAKE_BUILD_TYPE=Release ../
    - VERBOSE=1 make
    - OMP_NUM_THREADS=4 make -C tests/unit test || cat tests/unit/Testing/Temporary/LastTest.log / # "/" intentional! (just to make cat exit with an error code)
    - sudo make install
    - cd ../..
    
    # libcloudph++'s dependencies
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install --no-install-recommends -t trusty -y libboost-python-dev python-numpy libthrust-dev; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then git clone --depth=1 git://github.com/thrust/thrust.git; fi
    - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then sudo ln -s thrust/thrust /usr/local/include/thrust; fi

    # libcloudph++ (needed by icicle, skipping tests and CUDA build)
    - git clone --depth=1 git://github.com/igfuw/libcloudphxx.git
    - cd libcloudphxx
    - mkdir build 
    - cd build
    - if [[ $TRAVIS_OS_NAME == 'linux' && $CXX == 'clang++' ]]; then cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ ../; fi # Travis default is not the packaged     one
    - if [[ $TRAVIS_OS_NAME == 'osx' && $CXX == 'g++' ]]; then cmake -DCMAKE_CXX_COMPILER=g++-4.8 ../; fi # the one from homebrew
    - cmake -DCMAKE_BUILD_TYPE=Release ../ 
    - make 
    - sudo make install
    - cd ../..

    ## icicle (no tests - just testing if any changes in libmpdata's API did not break icicle)
    - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install --no-install-recommends -t trusty -y libboost-program-options-dev; fi
    - git clone --depth=1 git://github.com/igfuw/icicle.git
    - cd icicle
    - mkdir build 
    - cd build
    - if [[ $TRAVIS_OS_NAME == 'linux' && $CXX == 'clang++' ]]; then cmake -DCMAKE_CXX_COMPILER=/usr/bin/clang++ ../; fi # Travis default is not the packaged     one
    - if [[ $TRAVIS_OS_NAME == 'osx' && $CXX == 'g++' ]]; then cmake -DCMAKE_CXX_COMPILER=g++-4.8 ../; fi # the one from homebrew
    - cmake -DCMAKE_BUILD_TYPE=Release ../ 
    - make
